#!/usr/bin/python3
"""
Module that defines the MyList class that inherits from list.
"""

class MyList(list):
    """MyList class that inherits from the built-in list."""

    def print_sorted(self):
        """Prints the list, but sorted (ascending sort)."""
        print(sorted(self))
